### ISSUE TITLE
LoadError Trying to run plugin

### ISSUE THREAD

**Issue by avatar382** [dartmouth-dltg/aspace_content_warnings#2]
Hello,

I'm getting the following error trying to run this plugin:

```
LoadError: no such file to load -- /archivesspace/plugins/aspace_content_warnings/backend/lib/aspace_content_warnings_ead_overrides
```

I'm installing the plugin on an ArchivesSpace 3.4.1 instance running in Docker.

The plugin was initialized by running:

```
ASPACE_INITIALIZE_PLUGINS=aspace_content_warnings  docker start <docker_id>
```

I have verified that this initialization correctly ran the database migrations. 

I also checked the directory, and I don't see a file called "aspace_content_warnings_ead_overrides" anywhere in the directory structure.

**Comment by jdshaw** [comment]
Oops! Forgot to remove those old requires from the 3.4.0+ branch - the extra code they contained are now in core. Should be all set now.
